Support typescript
n-riesco/jp-babel pull request #21
Opened 2019-08-14 14:59 UTC by pbadenski

At the moment jp-babel doesn't work with TypeScript since babel does not by default include ".ts" in supported filename extensions (https://babeljs.io/docs/en/babel-core#default_extensions).

Additionally babel uses filename extensions to decide which presets should be enabled for a file and that was also not working.

We include to additional flags for jp-babel:
 - extensions - user can override file extensions to be transpiled by babel (this is passed down to @babel/register)
 - notebookLanguage - user can decide what language should be used to transpile notebook cells (instead of javascript which is the default)

This pull request combines all changes we did for our project to make jp-babel work.

This should also work for any other languages that babel can transpile, which are not enabled
in babel by default.

//cc @robh1

2019-10-10 10:11 UTC, n-riesco requested changes
We should add a section in the README showing how to use `jp-babel` with Typescript (what does the user need to install?)

Probably not in this PR, but we also need options to configure the kernel description for Jupyter:
https://github.com/n-riesco/jp-babel/blob/798fa9d419f50535a5a33fa9671e7ef9d74166e5/lib/kernel.js#L289-L294

2019-10-10 10:11 UTC, n-riesco commented on bin/rc.js
> +        );
Why do we need to set `filename` in the transform options?

2019-10-10 10:11 UTC, n-riesco commented on lib/kernel.js
> +        {}, transformOptions, {extensions: config.extensions}
Judging from https://babeljs.io/docs/en/babel-register , I don't think `transformOptions` belongs here.
`var registerOptions = {extensions: config.extensions};` should be enough.

2019-10-10 10:11 UTC, n-riesco commented on lib/kernel.js
> +log("transformOptions:", transformOptions);
Please, add `log("registerOptions:", registerOptions);`

2019-10-10 10:11 UTC, n-riesco commented on lib/kernel.js
> +    var transpiledCode = transform(code, optionsWithFilename).code;
See above question about the need for `filename`?

2019-10-10 10:11 UTC, n-riesco commented on lib/kernel.js
> +        notebookLanguage: "js"
See above question about the need for `filename`?

2019-10-10 10:11 UTC, n-riesco commented on lib/kernel.js
> +        }],
See above question about the need for `filename`?

2019-10-14 13:23 UTC, pbadenski commented on bin/rc.js
> +        );
babel-preset-typescript is switched on with a file extension check: https://github.com/babel/babel/blob/master/packages/babel-preset-typescript/src/index.js#L35.

I needed something to nudge babel to treat all coming language as TypeScript.

2019-10-14 13:26 UTC, pbadenski commented on lib/kernel.js
> +        {}, transformOptions, {extensions: config.extensions}
I think you're right, I removed it and all works fine.

2019-10-14 13:27 UTC, pbadenski commented on lib/kernel.js
> +log("transformOptions:", transformOptions);
Sure, will do.

2019-10-14 23:26 UTC, n-riesco commented on bin/rc.js
> +        );
OK, I understand, but how about setting `allExtensions` to `true` in `.babelrc` instead? In this way, `jp-babel` wouldn't need to set `--filename`.

```json
{
  "presets": [
    [
      "@babel/preset-typescript",
      {
        "allExtensions": true
      }
    ]
  ]
}
```

---

By the way, if this flag (`--notebook-language`)  turns out to be really unavoidable, I'd like to name it `--filename` (for consistency with babel).

2019-10-14 23:39 UTC, n-riesco commented on bin/rc.js
> +        );
In fact, if setting `allExtensions` to `true` works, then this whole PR won't be necessary.

---

I still think, though, that it'd be a good idea to add a section in the README, explaining how to use `jp-babel` as a typescript kernel, even if it's only a question of setting `.babelrc`.

2019-10-18 11:32 UTC, pbadenski commented on bin/rc.js
> +        );
Point taken. It certainly works for our project. Do you want to close the pull request then? I can add a README upgrade separately if you're keen on this.

2019-10-18 12:56 UTC, n-riesco commented
@pbadenski Thank your for all the work on this PR and this review. But, since setting `allExtensions` to `true` seems to do the trick, I prefer this option over having more code to maintain.

I'd certainly welcome a PR to document your use of `jp-babel` and Typescript.

2019-10-18 12:56 UTC, closed without merging